# My first Notebook

In [44]:
import sys
import numpy as np
import pandas as pd

arr = [1,2,3]
print(np.array(arr));


[1 2 3]


In [13]:
arr[0], arr[1]

(1, 2)

In [14]:
C = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
C[1][1] #multi indexing

5

In [16]:
C[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [17]:
C[:1]

array([[1, 2, 3]])

In [18]:
C[1,1]

5

In [19]:
C.sum()

45

In [20]:
C.sum(axis=0) #menghitung jumlah setiap kolom (1 + 4 + 7) (2 + 5 + 8) (3 + 6 + 9)

array([12, 15, 18])

In [21]:
C.sum(axis=1) # menghitung jumlah setiap baris

array([ 6, 15, 24])

In [22]:
C.mean() # menghitung rata-rata 

5.0

In [23]:
C.mean(axis=0)

array([4., 5., 6.])

In [24]:
C.std(axis=0) # menghitung deviasi standard -> ukuran statistik yang mengukur sebaran data atau sejauh mana data tersebar dari nilai rata-ratanya.

array([2.44948974, 2.44948974, 2.44948974])

In [25]:
arr = [1,2,3,4,5,6,7,8,9,10]
for i in arr :
    print(i)

1
2
3
4
5
6
7
8
9
10


# Broadcasting and vectorized operations

In [11]:
a = np.arange(4) #membuat array dari 0 sampai 3
a

array([0, 1, 2, 3])

In [26]:
b = np.arange(4, 10)
b

array([4, 5, 6, 7, 8, 9])

In [28]:
c = np.arange(4, 10, 2)
c

array([4, 6, 8])

In [8]:
a + 10

array([10, 11, 12, 13])

In [9]:
a * 10

array([ 0, 10, 20, 30])

In [3]:
x = np.arange(5)
x + 20

array([20, 21, 22, 23, 24])

# Boolean Array

In [6]:
boolArr = np.arange(5)
boolArr

array([0, 1, 2, 3, 4])

In [12]:
boolArr[[0, 1]]

array([0, 1])

In [16]:
boolArr[[True, False, False, True, False]]

array([0, 3])

In [17]:
boolArr >= 2

array([False, False,  True,  True,  True])

In [18]:
boolArr[boolArr >= 2]

array([2, 3, 4])

In [19]:
boolArr.mean()

2.0

In [20]:
boolArr[ boolArr > boolArr.mean() ]

array([3, 4])

In [23]:
boolArr[~(a > a.mean())] # (~) symbol is NOT operator

array([0, 1, 2])

In [26]:
boolArr[(boolArr == 0) | (boolArr == 1)]

array([0, 1])

In [32]:
A = np.random.randint(100, size=(3,3)) #membuat matriks menggunakan angka random
A

array([[18, 49,  7],
       [ 2, 15, 85],
       [99, 49,  3]])

In [33]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([18,  7, 15, 99,  3])

In [34]:
A > 30

array([[False,  True, False],
       [False, False,  True],
       [ True,  True, False]])

In [35]:
A[A > 30]

array([49, 85, 99, 49])

# Linear Algebra

In [36]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [38]:
B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [39]:
A.dot(B) #dot function is used to matrix multiplication

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [40]:
A @ B # '@' is the alternative for matrix multiplication

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [41]:
B.T #transpose . In indonesian is membalikkan

array([[1, 3, 5],
       [2, 4, 6]])

In [43]:
B.T @ A

array([[48, 57, 66],
       [60, 72, 84]])

# Size of objects in Memory

In [48]:
sys.getsizeof(3)

28

In [49]:
sys.getsizeof(10**100)

72

In [50]:
np.dtype(int).itemsize

4

In [51]:
np.dtype(float).itemsize

8

## List are even larger

In [52]:
sys.getsizeof([1])

64

In [53]:
np.array([1]).nbytes

4

## And performance is also important

In [58]:
l = list(range(100000)) # jadi l itu berisi angka yang digenerate 0 sampai 100000 dan list menggunakan list function 

In [61]:
w = np.arange(100000)

In [62]:
%time np.sum(w ** 2)

CPU times: total: 0 ns
Wall time: 2 ms


216474736

In [63]:
%time sum([x ** 2 for x in l])

CPU times: total: 31.2 ms
Wall time: 60.6 ms


333328333350000

# Useful Numpy functions 

### random

In [66]:
np.random.random(size=2)

array([0.76299107, 0.72372323])

In [67]:
np.random.normal(size=2)

array([-1.183524  ,  0.95685667])

In [68]:
np.random.rand(2,4)

array([[0.16036611, 0.36516897, 0.96263834, 0.42453866],
       [0.03019131, 0.38260757, 0.94692397, 0.69541408]])

### arange

In [69]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [73]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

In [74]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [76]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [77]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [78]:
np.linspace(0,1,20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [79]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [80]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.zeros((3,3), dtype=np.int)

C:\Users\Widura\AppData\Local\Temp\ipykernel_1784\179700837.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3,3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [82]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### identity and eye

In [83]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [92]:
"Hello World"[6]

'W'